/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Mergify backend API for one repository, over the shared async client.
 *
 * Every method returns a Promise (napi drives the future on its own tokio
 * runtime). The fetches are tri-state, flattened to JS the same way the `PyO3`
 * binding flattens them to Python: the value when the feature is enabled,
 * `null` when the server says it is not (a dormant `402`/`404`), and a
 * rejection on a genuine failure. Trace upload fails loud.
 */
export declare class CiApiClient {
  /**
   * Build a client for one repository. Throws when `repoName` is not an
   * `owner/repo` pair, or when the HTTP client cannot be built.
   */
  constructor(options: ApiClientOptions)
  /**
   * The quarantined test names for `branch`, or `null` when quarantine is
   * not enabled for the repository.
   */
  fetchQuarantine(branch: string): Promise<Array<string> | null>
  /**
   * The flaky-detection context, or `null` when it is not enabled for the
   * repository.
   */
  fetchFlakyContext(): Promise<FlakyDetectionContext | null>
  /**
   * The test selection for a run, identified by its own `branch`,
   * `headSha` and job coordinates, or `null` when test selection is not
   * enabled for the repository.
   *
   * `collectionFingerprint` is the identity of what this run collected
   * (`testCollectionFingerprint`): a subset is only safe to serve to a run
   * that collects the same tests the previous attempt did, so a request
   * without one is answered with the full suite. Optional so a caller that
   * holds no collection at the moment it asks (Vitest collects inside its
   * workers) sends no parameter at all rather than claiming an empty one.
   */
  fetchTestSelection(branch: string, headSha: string, pipelineName: string, jobName: string, collectionFingerprint?: string | undefined | null): Promise<TestSelection | null>
  /**
   * Upload `spans` under `resourceAttributes` as gzipped OTLP protobuf,
   * splitting oversized traces across several uploads. Rejects on failure.
   */
  uploadTrace(resourceAttributes: Array<Attribute>, spans: Array<Span>): Promise<void>
}

/**
 * How to reach one repository's Mergify backend API, and who is calling.
 *
 * The calling *distribution* is named by the plugin rather than fixed here:
 * unlike the pytest wheel, this binding is shared by `@mergifyio/vitest` and
 * `@mergifyio/playwright`, and the backend counts them separately.
 */
export interface ApiClientOptions {
  /** API base URL (`MERGIFY_API_URL`, default `https://api.mergify.com`). */
  apiUrl: string
  /** Bearer token (`MERGIFY_TOKEN`). */
  token: string
  /** The repository as `owner/repo`. */
  repoName: string
  /** The npm package calling, e.g. `@mergifyio/vitest`. */
  clientName: string
  /** That package's version. */
  clientVersion: string
  /** `process.versions.node`, reported as the runtime in the `User-Agent`. */
  nodeVersion: string
}

/** One `OpenTelemetry` attribute, as a key and a JS `boolean | number | string`. */
export interface Attribute {
  key: string
  value: boolean | number | string
}

/** The tests flaky detection reruns this session, and the budget for them. */
export interface BudgetPlan {
  /** Total rerun budget for the session, in milliseconds. */
  availableBudgetMs: number
  /** The selected tests, in the order they were given. */
  testsToProcess: Array<string>
}

/**
 * Select the tests flaky detection reruns and compute the session's budget.
 *
 * `excluded` holds the tests that opted out. The budget scales with the
 * baseline tests present in this session, floored at `min_budget_duration_ms`.
 */
export declare function computeBudget(context: FlakyDetectionContext, mode: string, sessionTests: Array<string>, excluded: Array<string>): BudgetPlan

/**
 * Select the tests test retry answers for and compute its session budget.
 *
 * `testsBeingDetected` is flaky detection's target set, and
 * `detectionGatesFailures` says a failure of those reruns is itself the merge
 * gate (`"new"` mode), where retry gives up the verdict rather than absorbing
 * it. See `budget::retry_plan` for the rules the two lists encode.
 */
export declare function computeRetryBudget(context: FlakyDetectionContext, sessionTests: Array<string>, excluded: Array<string>, testsBeingDetected: Array<string>, detectionGatesFailures: boolean): RetryPlan

/**
 * The OTel resource attributes for this run, as a dotted-key map (`cicd.*`,
 * `vcs.*`, `mergify.test.job.name`) with string or number values — integer
 * attributes like `cicd.pipeline.run.id` (GitHub) and
 * `cicd.pipeline.run.attempt` arrive as JS numbers. Provider-scoped
 * attributes are suppressed outside CI; `mergify.test.job.name` is always-on
 * when `MERGIFY_TEST_JOB_NAME` is set. When in CI, the provider's
 * environment is read first and the git CLI fills whatever it didn't supply
 * (head branch/revision, remote URL). Same shape as Rust's
 * `CiResourceAttributes` and Python's `detect_attributes()` dict; the
 * semconv keys flow through untouched, so `otel.rs` stays their single
 * source of truth.
 */
export declare function detectAttributes(): Record<string, number | string>

/**
 * The detected CI provider, or `null` when not running in a recognized CI.
 * The first provider whose detection variable (`GITHUB_ACTIONS`, `CIRCLECI`,
 * `JENKINS_URL`, `BUILDKITE`) is present *and* truthy wins — a
 * present-but-falsy value like `GITHUB_ACTIONS=false` is skipped, not a
 * match. Returns the stable name emitted as `cicd.provider.name`:
 * `github_actions`, `circleci`, `jenkins`, or `buildkite`. Reads the
 * environment at call time.
 */
export declare function detectProvider(): string | null

/**
 * The API-endpoint `owner/repo` used for CI Insights calls, or `null` when
 * undeterminable. Resolved from the active provider's environment first —
 * `GITHUB_REPOSITORY` on GitHub Actions, parsed from `CIRCLE_REPOSITORY_URL`
 * on CircleCI, `GIT_URL` on Jenkins, `BUILDKITE_REPO` on Buildkite — falling
 * back to parsing the working directory's `origin` git remote when no
 * provider is active. Can legitimately differ from the
 * `vcs.repository.name` *attribute* (e.g. on CircleCI the endpoint comes
 * from the env URL while the attribute may come from the git remote).
 */
export declare function detectRepositoryName(): string | null

/** The per-test slice recomputed from what is left, as the session progresses. */
export declare function dynamicShareMs(availableBudgetMs: number, usedBudgetMs: number, numTests: number, processed: number): number

/**
 * The flaky-detection context: the server's baseline and budget parameters.
 *
 * The field names stay `snake_case` (`js_name`) because this object *is*
 * `@mergifyio/ci-core`'s public `FlakyDetectionContext` — it is accepted as a
 * reporter option and persisted in the Playwright state file. It is also the
 * wire contract shared with pytest-mergify, so the keys match the API's.
 */
export interface FlakyDetectionContext {
  budget_ratio_for_new_tests: number
  budget_ratio_for_unhealthy_tests: number
  existing_test_names: Array<string>
  existing_tests_mean_duration_ms: number
  unhealthy_test_names: Array<string>
  budget_ratio_for_test_retries?: number
  flaky_test_names?: Array<string>
  broken_test_names?: Array<string>
  max_test_execution_count: number
  max_test_name_length: number
  min_budget_duration_ms: number
  min_test_execution_count: number
}

/** The tests test retry answers for, and the budget it may spend on them. */
export interface RetryPlan {
  /** Total retry budget for the session, in milliseconds. */
  availableBudgetMs: number
  /**
   * Every test whose failure retry owns the verdict for — including the ones
   * it will not pay to rerun.
   */
  eligibleTests: Array<string>
  /** The eligible tests retry reruns on its own budget. */
  testsToProcess: Array<string>
}

/**
 * Whether flaky detection has anything to do this session — `false` in
 * `"new"` mode with an empty baseline, where every test would look new and
 * the whole suite would rerun.
 */
export declare function shouldRunFlakyDetection(context: FlakyDetectionContext, mode: string): boolean

/**
 * One finished span, handed over as plain data — no live `OpenTelemetry`
 * objects cross the boundary. Ids are the lowercase hex strings the JS SDK
 * already exposes on a span context; timestamps are `bigint` because
 * nanoseconds since the epoch exceed what a JS `number` holds exactly.
 */
export interface Span {
  name: string
  /** 32 hex characters. */
  traceId: string
  /** 16 hex characters. */
  spanId: string
  /** 16 hex characters, or `null` for a root span. */
  parentSpanId?: string
  startUnixNano: bigint
  endUnixNano: bigint
  attributes: Array<Attribute>
  /** `"unset"`, `"ok"`, or `"error"`. */
  status: string
  /** The error description; only read when `status` is `"error"`. */
  statusMessage?: string
}

/** The per-test slice when the budget is split evenly up front. */
export declare function staticShareMs(availableBudgetMs: number, numTests: number): number

/**
 * The identity of the set of tests a run collected: the same digest
 * pytest-mergify reports, from the same core recipe
 * (`mergify_ci_core::test_collection_fingerprint`), so Mergify can match a
 * rerun's collection against the previous attempt's whatever client uploaded
 * it. Order-independent; a repeated identifier is a different collection.
 */
export declare function testCollectionFingerprint(testIds: Array<string>): string

/**
 * Whether this run should execute only a subset of tests.
 *
 * Left as the server sent it, deliberately: only the caller holds the tests
 * the framework actually collected, and normalising `subset` down to `full`
 * (an empty list, a list matching nothing) is a decision that needs them. The
 * binding's job is to deliver the answer, not to interpret it.
 */
export interface TestSelection {
  /**
   * `"full"` (run everything), `"subset"` (run only `tests`), `"empty"`
   * (run nothing: the previous attempt of this job ran these tests and they
   * passed), `"refused"` (Mergify will not guess between several candidate
   * sessions; the run must fail), or a value this client predates. Handed
   * over verbatim: what to do with an answer the run cannot honour is
   * decided by the plugin, which declares it rather than rewriting it.
   */
  selection: string
  /** Why the server chose this selection — surfaced in the plugin report. */
  reason: string
  /** The test identifiers to run; absent on every answer but a `subset`. */
  tests?: Array<string>
  /**
   * The server's own explanation to show the CI user, when the answer has
   * one — today only a refusal does. Shown verbatim: the copy is the
   * server's so it can be corrected without publishing a client.
   */
  message?: string
}
