/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The OTel resource attributes for this run, as a dotted-key map (`cicd.*`,
 * `vcs.*`, `mergify.test.job.name`) with string or number values — integer
 * attributes like `cicd.pipeline.run.id` (GitHub) and
 * `cicd.pipeline.run.attempt` arrive as JS numbers. Provider-scoped
 * attributes are suppressed outside CI; `mergify.test.job.name` is always-on
 * when `MERGIFY_TEST_JOB_NAME` is set. When in CI, the provider's
 * environment is read first and the git CLI fills whatever it didn't supply
 * (head branch/revision, remote URL). Same shape as Rust's
 * `CiResourceAttributes` and Python's `detect_attributes()` dict; the
 * semconv keys flow through untouched, so `otel.rs` stays their single
 * source of truth.
 */
export declare function detectAttributes(): Record<string, number | string>

/**
 * The detected CI provider, or `null` when not running in a recognized CI.
 * The first provider whose detection variable (`GITHUB_ACTIONS`, `CIRCLECI`,
 * `JENKINS_URL`, `BUILDKITE`) is present *and* truthy wins — a
 * present-but-falsy value like `GITHUB_ACTIONS=false` is skipped, not a
 * match. Returns the stable name emitted as `cicd.provider.name`:
 * `github_actions`, `circleci`, `jenkins`, or `buildkite`. Reads the
 * environment at call time.
 */
export declare function detectProvider(): string | null

/**
 * The API-endpoint `owner/repo` used for CI Insights calls, or `null` when
 * undeterminable. Resolved from the active provider's environment first —
 * `GITHUB_REPOSITORY` on GitHub Actions, parsed from `CIRCLE_REPOSITORY_URL`
 * on CircleCI, `GIT_URL` on Jenkins, `BUILDKITE_REPO` on Buildkite — falling
 * back to parsing the working directory's `origin` git remote when no
 * provider is active. Can legitimately differ from the
 * `vcs.repository.name` *attribute* (e.g. on CircleCI the endpoint comes
 * from the env URL while the attribute may come from the git remote).
 */
export declare function detectRepositoryName(): string | null
