/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The detected CI context as JSON: `provider` and `repositoryName` (both
 * nullable) plus the OTel resource `attributes` map (string or integer
 * values). JSON keeps the binding surface to a single string-returning
 * function — the TS side owns the typing.
 */
export declare function detectJson(): string
